<hmtl><?php $icon = "http://learnwhentoquit/emj/echo.gif"; $postype = "drpost";
$battle_screen = "boxboss"; $enemy_image = "006-Discord.png"; $soulR = 66; $soulG = 252; $soulB = 255;
$button1 = "index.php"; $button2 = "001.php"; $button3 = "005.php"; $button4 = "007.php";
$chaptercheck = '<ul class="dlgsdt"><li>...</li></ul>';
$chnum = "006"; $title = "The Prompter Echoed on May 1, 2016"; ?>
<head><title>LWtQ - <?= $title ?></title><link rel="shortcut icon"href="<?= $icon ?>"><?php include('css/screensize.php'); ?></head><body>
<!--
     ██████ ██   ██  █████  ██████  ████████ ███████ ██████
    ██      ██   ██ ██   ██ ██   ██    ██    ██      ██   ██
    ██      ███████ ███████ ██████     ██    █████   ██████
    ██      ██   ██ ██   ██ ██         ██    ██      ██   ██
     ██████ ██   ██ ██   ██ ██         ██    ███████ ██   ██
-->
<div id="post_container"><div class="dispost" id="phonindex1"><?php include('css/UTbattlescreen.php'); ?></div>

<a href="javascript:SwapDivsWithClick('pecheck1-1','pecheck1-2')"><div class="dispost" id="pecheck1-1"><peboxblink></peboxblink></div></a>
<a href="javascript:SwapDivsWithClick('pecheck1-2','pecheck1-3')"><div class="dispost" id="pecheck1-2" style="display:none;"><pebox><ul class="dlgsdt"><li>...</li></ul></pebox></div></a>
<a href="javascript:SwapDivsWithClick('pecheck1-3','pecheck1-4')"><div class="dispost" id="pecheck1-3" style="display:none;"><pebox><ul class="dlgsdt"><li>There is nothing to see here.</li></ul></pebox></div></a>
<a href="javascript:SwapDivsWithClick('pecheck1-4','pecheck1-5')"><div class="dispost" id="pecheck1-4" style="display:none;"><pebox><ul class="dlgsdt"><li>...</li></ul></pebox></div></a>
<a href="javascript:SwapDivsWithClick('pecheck1-5','pecheck1-6')"><div class="dispost" id="pecheck1-5" style="display:none;"><pebox><ul class="dlgsdt"><li>There is no witness to recount these events.</li></ul></pebox></div></a>
<a href="javascript:SwapDivsWithClick('pecheck1-6','pecheck1-7')"><div class="dispost" id="pecheck1-6" style="display:none;"><pebox><ul class="dlgsdt"><li>...</li></ul></pebox></div></a>
<a href="javascript:SwapDivsWithClick('pecheck1-7','pecheck1-8')"><div class="dispost" id="pecheck1-7" style="display:none;"><pebox><ul class="dlgsdt"><li>But, perhaps...</li></ul></pebox></div></a>
<a href="javascript:SwapDivsWithClick('pecheck1-8','pecheck1-9')"><div class="dispost" id="pecheck1-8" style="display:none;"><pebox><ul class="dlgsdt"><li>Can a story still exist, even without anyone to narrate it?</li></ul></pebox></div></a>
<a href="javascript:SwapDivsWithClick('pecheck1-9','pecheck1-10')"><div class="dispost" id="pecheck1-9" style="display:none;"><pebox><ul class="dlgsdt"><li>...</li></ul></pebox></div></a>
<a href="javascript:SwapDivsWithClick('pecheck1-10','pecheck1-11')"><div class="dispost" id="pecheck1-10" style="display:none;"><pebox><ul class="dlgsdt"><li>It is faint, but...</li></ul></pebox></div></a>
<a href="javascript:SwapDivsWithClick('pecheck1-11','pecheck1-12')"><div class="dispost" id="pecheck1-11" style="display:none;"><pebox><ul class="dlgsdt"><li>From afar, if one listens closely...</li></ul></pebox></div></a>
<a href="javascript:SwapDivsWithClick('pecheck1-12','006-full')"><div class="dispost" id="pecheck1-12" style="display:none;"><pebox><ul class="dlgsdt"><li>Distant whispers of unseen events are echoing from somewhere else.</li></ul></pebox></div></a>
<div id="006-full" style="display:none;">
<?php include('css/intro.php'); ?>
<div class="dispost" id="chapter">
    <table class="distitle"><tr><td width="80px;"><img class="icon" src="img/pfp_TVF_server.gif"></td><td>Can You Really Call This TVF's Official Server, I&nbsp;Didn't See Any Temmies Or Anything</td></tr></table>
    <table class="disheader"><tr><td><img src="ast/disheader_general_channel.png"></td></tr></table>
    <table class="disut">
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 1:48 PM</dtime><br>Guys, did any of you hear about Harlonkie's last twitch stream?<br>The one where he does some sort of weird magic trick for no reason and then nobody hears from him again so he just lets us try to figure out what happened? :/</td></tr>
        <tr><td><img class="icon" src="img/pfp_artie.png"></td><td><pfp><gso>CoolSkeleton03</gso></pfp> <dtime>May 1, 2016 1:49 PM</dtime><br>Dude<br>That happened like forever ago right?<br>Personally i never watched him but uh<br>Whatever if he wants to get some attention by doing the creepy mysterious stunt and making himself victim of some sort of cheap creepypasta what do you want me to say<br>Are people still talking about it???</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 1:50 PM</dtime><br>I don't know, my tumblr dash is still clogged with some theories and stuff about it every now and then<br>and when I did some research about what that was about it looked like a serious thing ._.</td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td colspan="2"><ul class="dlgmdt" style="color:#edd91a;margin-left:24px;"><li class="sts"><oso>BlueDoppler</oso> is now online. <dtime>May 1, 2016 1:52 PM</dtime></li></ul></td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 1:52 PM</dtime><br>Oh hey Lys!<br>By any chance, do you know some stuff about Harlonkie's "ghost livestream" that was never recorded or uploaded?</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 1:53 PM</dtime><br>Hahaha<br>HAHAHA!</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 1:53 PM</dtime><br>uh</td></tr>
        <tr><td><img class="icon" src="img/pfp_artie.png"></td><td><pfp><gso>CoolSkeleton03</gso></pfp> <dtime>May 1, 2016 1:54 PM</dtime><br>?</td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td colspan="2"><ul class="dlgmdt" style="color:#edd91a;margin-left:24px;"><li class="sts"><bso>KangarooBrush</bso> is now online. <dtime>May 1, 2016 1:54 PM</dtime></li></ul></td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 1:54 PM</dtime><br>ok</td></tr>
        <tr><td><img class="icon" src="img/pfp_kb.png"></td><td><pfp><bso>KangarooBrush</bso></pfp> <dtime>May 1, 2016 1:54 PM</dtime><br>Hello to you too, Lys :')</td></tr>
        <tr><td><img class="icon" src="img/pfp_isabel.png"></td><td><pfp><oso>Calliope Quill</oso></pfp> <dtime>May 1, 2016 1:54 PM</dtime><br>Oh, there we go.</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 1:54 PM</dtime><br>Guys, I did it!<br>I finally DID IT!!</td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td colspan="2"><ul class="dlgmdt" style="color:#edd91a;margin-left:24px;"><li class="sts"><rso>WinDows Gulim</rso> is now online. <dtime>May 1, 2016 1:54 PM</dtime></li></ul></td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td><img class="icon" src="img/pfp_isabel.png"></td><td><pfp><oso>Calliope Quill</oso></pfp> <dtime>May 1, 2016 1:55 PM</dtime><br>It appears that Doppler is finally divulging to the wide world the dormant mad scientist who dwells threateningly in the meanderings of her mind.<br>Take cover, everybody.</td></tr>
        <tr><td><img class="icon" src="img/pfp_kb.png"></td><td><pfp><bso>KangarooBrush</bso></pfp> <dtime>May 1, 2016 1:56 PM</dtime><br>Isabel, please...</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 1:56 PM</dtime><br>Oh shut up already, Quill. Not now.<br>This moment is too perfect and I don't need you to ruin it.</td></tr>
        <tr><td><img class="icon" src="img/pfp_wdg.png"></td><td><pfp><rso>WinDows Gulim</rso></pfp> <dtime>May 1, 2016 1:56 PM</dtime><br>What's the matter, Lys?</td></tr>
        <tr><td><img class="icon" src="img/pfp_artie.png"></td><td><pfp><gso>CoolSkeleton03</gso></pfp> <dtime>May 1, 2016 1:56 PM</dtime><br>Just 2 mins in and i already have no idea what's going on anymore<br>Like wow</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 1:57 PM</dtime><br>This is FINALLY happening, guys. I'm not kidding.</td></tr>
        <tr><td><img class="icon" src="img/pfp_isabel.png"></td><td><pfp><oso>Calliope Quill</oso></pfp> <dtime>May 1, 2016 1:57 PM</dtime><br>Now I'm the lost one. What have we been allegedly "hyping" for?</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 1:57 PM</dtime><br>Dawn. She's finally doing it.</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 1:57 PM</dtime><br>OMG</td></tr>
        <tr><td><img class="icon" src="img/pfp_artie.png"></td><td><pfp><gso>CoolSkeleton03</gso></pfp> <dtime>May 1, 2016 1:58 PM</dtime><br>Whaaaaaat?</td></tr>
        <tr><td><img class="icon" src="img/pfp_wdg.png"></td><td><pfp><rso>WinDows Gulim</rso></pfp> <dtime>May 1, 2016 1:58 PM</dtime><br>Noo... Really?</td></tr>
        <tr><td><img class="icon" src="img/pfp_isabel.png"></td><td><pfp><oso>Calliope Quill</oso></pfp> <dtime>May 1, 2016 1:58 PM</dtime><br>Still in the dark here.</td></tr>
        <tr><td><img class="icon" src="img/pfp_wdg.png"></td><td><pfp><rso>WinDows Gulim</rso></pfp> <dtime>May 1, 2016 1:58 PM</dtime><br>Oh Glob, I'm so proud of you right now. How did you do it?</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 1:58 PM</dtime><br>Sometimes blackmail is for the greater good =)</td></tr>
        <tr><td><img class="icon" src="img/pfp_kb.png"></td><td><pfp><bso>KangarooBrush</bso></pfp> <dtime>May 1, 2016 1:58 PM</dtime><br>Aaw, geez... :')</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 1:58 PM</dtime><br>And now she HAS to play it \o/</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 1:59 PM</dtime><br>ON LIVESTREAM!<br>I WANNA SEE THIS OMG</td></tr>
        <tr><td><img class="icon" src="img/pfp_isabel.png"></td><td><pfp><oso>Calliope Quill</oso></pfp> <dtime>May 1, 2016 1:59 PM</dtime><br>... Right. The "Plup Game."<br>Oh boy.</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 1:59 PM</dtime><br>LET'S START THE CALL RIGHT NOW!</td></tr>
        <tr><td><img class="icon" src="img/pfp_wdg.png"></td><td><pfp><rso>WinDows Gulim</rso></pfp> <dtime>May 1, 2016 1:59 PM</dtime><br>Yosh, she's not even online yet x)</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:00 PM</dtime><br>THEN WHAT ARE YOU WAITING FOR??? LYS JUST BRING HER ALREADY!<br>You're in her house now, right? o3o</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 2:00 PM</dtime><br>Nah, we had lunch together but now I'm back home with my laptop and all.<br>But she should be here in... Maybe a few more minutes?</td></tr>
        <tr><td><img class="icon" src="img/pfp_dawn.png"></td><td><pfp><gso>Pineapplup</gso></pfp> <dtime>May 1, 2016 2:00 PM</dtime><br>Guess again, Lys. I was stalking.</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:00 PM</dtime><br>YUIFDRTDKJBVFGFJGH</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 2:00 PM</dtime><br>... Oh.</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:00 PM</dtime><br>A WILD PIPLUP APPEARED!!!</td></tr>
        <tr><td><img class="icon" src="img/pfp_dawn.png"></td><td><pfp><gso>Pineapplup</gso></pfp> <dtime>May 1, 2016 2:01 PM</dtime><br>And I <yga>REALLY</yga> want you to give it back as soon as this is over. I'm counting on you.</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><div><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 2:01 PM</dtime><br>Don't worry Dawn, it's safe.<br>C'mon, you can trust me!<br>I'll take good care of it <img class="emoji" src="http://learnwhentoquit/emj/sans_wink.png"></div></td></tr>
        <tr><td><img class="icon" src="img/pfp_dawn.png"></td><td><pfp><gso>Pineapplup</gso></pfp> <dtime>May 1, 2016 2:01 PM</dtime><br>That's exactly what I fear...</td></tr>
        <tr><td><img class="icon" src="img/pfp_wdg.png"></td><td><pfp><rso>WinDows Gulim</rso></pfp> <dtime>May 1, 2016 2:01 PM</dtime><br>It's alright, Dawn. She'll give back... whatever it is she took from you.</td></tr>
        <tr><td><img class="icon" src="img/pfp_dawn.png"></td><td><pfp><gso>Pineapplup</gso></pfp> <dtime>May 1, 2016 2:01 PM</dtime><br>Yeah yeah, whatever.<br>btw, hi joystick</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:02 PM</dtime><br>HIIIIIIII<br>SO ARE YOU DOING THAT LIVESTREAM OR NOT??? :DDD</td></tr>
        <tr><td><img class="icon" src="img/pfp_dawn.png"></td><td><pfp><gso>Pineapplup</gso></pfp> <dtime>May 1, 2016 2:02 PM</dtime><br>...°sigh°<br>I guess I don't have a choice uh.</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:02 PM</dtime><br>no u don't <img class="emoji" src="http://learnwhentoquit/emj/onionsan.png"></td></tr>
        <tr><td><img class="icon" src="img/pfp_dawn.png"></td><td><pfp><gso>Pineapplup</gso></pfp> <dtime>May 1, 2016 2:02 PM</dtime><br>...<br>welp<br>Lys, do you mind if I use your Steam account and reset your game?</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 2:02 PM</dtime><br>You know I don't :p</td></tr>
        <tr><td><img class="icon" src="img/pfp_dawn.png"></td><td><pfp><gso>Pineapplup</gso></pfp> <dtime>May 1, 2016 2:02 PM</dtime><br>heh<br>I hate yall. Cant believe youd betray me like this.<br>but eh why the heck not<br>Well, I'll see you guys in a few minutes I guess.<br>In the meantime you can prepare the popcorn or whatever</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:02 PM</dtime><br>eeeeeeeee I can't wait!!! <img class="emoji" src="http://learnwhentoquit/emj/soul.png"></td></tr>
        <tr><td><img class="icon" src="img/pfp_isabel.png"></td><td><pfp><oso>Calliope Quill</oso></pfp> <dtime>May 1, 2016 2:03 PM</dtime><br>Well, I'll be off and leave you to... whatever it is you're about to do.<br>For my part there's still a chapter I'd like to finish today.</td></tr>
        <tr><td><img class="icon" src="img/pfp_artie.png"></td><td><pfp><gso>CoolSkeleton03</gso></pfp> <dtime>May 1, 2016 2:03 PM</dtime><br>Oh nice!! Will you review my fanfic too when ur done?</td></tr>
        <tr><td><img class="icon" src="img/pfp_isabel.png"></td><td><pfp><oso>Calliope Quill</oso></pfp> <dtime>May 1, 2016 2:03 PM</dtime><br>...<br>No.<br>I was about to type a sarcastic comment about the relevance of your writing style, but then I realized it probably wasn't worth the effort.</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:03 PM</dtime><br>Duh. Not everyone types in chatrooms the same way they write novels, Dickens.<br>Especially when they're on their phone lmao</td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td colspan="2"><ul class="dlgmdt" style="color:#e91d20;margin-left:24px;"><li class="sts"><oso>Calliope Quill</oso> is now offline. <dtime>May 1, 2016 2:03 PM</dtime></li></ul></td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td><img class="icon" src="img/pfp_wdg.png"></td><td><pfp><rso>WinDows Gulim</rso></pfp> <dtime>May 1, 2016 2:03 PM</dtime><br>Agreed. Phone keyboards are the worst <_<</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:05 PM</dtime><br>btw Artie, I <rga style="font-family:mfriend;text-shadow: 1px 1px 0 #800000, -1px 1px 0 #800000, 1px -1px 0 #800000, -1px -1px 0 #800000, 0px 1px 0 #800000, 0px -1px 0 #800000, -1px 0px 0 #800000, 1px 0px 0 #800000,
        2px 2px 0 #800000, -2px 2px 0 #800000, 2px -2px 0 #800000, -2px -2px 0 #800000, 0px 2px 0 #800000, 0px -2px 0 #800000, -2px 0px 0 #800000, 2px 0px 0 #800000, 1px 2px 0 #800000,
        -1px 2px 0 #800000, 1px -2px 0 #800000, -1px -2px 0 #800000, 2px 1px 0 #800000, -2px 1px 0 #800000, 2px -1px 0 #800000, -2px -1px 0 #800000;">LO-o-O-o-OVE</rga> how your story is going so far, I really think it's great!! Don't let the grinch make you think otherwise <img class="emoji" src='http://learnwhentoquit/emj/undyne_smug.png'></td></tr>
        <tr><td><img class="icon" src="img/pfp_artie.png"></td><td><pfp><gso>CoolSkeleton03</gso></pfp> <dtime>May 1, 2016 2:05 PM</dtime><br>...uh...</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:05 PM</dtime><br>...<br>Why.<br>Just why.<br>WDG, care to explain what this is? xD</td></tr>
        <tr><td><img class="icon" src="img/pfp_wdg.png"></td><td><pfp><rso>WinDows Gulim</rso></pfp> <dtime>May 1, 2016 2:06 PM</dtime><br>Looks like Lee made another autocorrect bot without telling me. Let me check<br>... Yeah, can confirm, he added <code>love</code> to the list of words to replace with random code</td></tr>
        <tr><td><img class="icon" src="img/pfp_artie.png"></td><td><pfp><gso>CoolSkeleton03</gso></pfp> <dtime>May 1, 2016 2:06 PM</dtime><br>Did he take it from a new meme or something<br>Better question is does he think it's funny</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:06 PM</dtime><br>Dang it the song is stuck in my head now<br>How do you two even find the time to code that stuff in lmao</td></tr>
        <tr><td><img class="icon" src="img/pfp_wdg.png"></td><td><pfp><rso>WinDows Gulim</rso></pfp> <dtime>May 1, 2016 2:06 PM</dtime><br>Well, coding it isn't that hard, it's basically the same bot as the one that replaces italics and bold text with the yellow and red from Undertale and changes the font of member names to Determination Mono. But to answer the "why"... I guess he probably did it on a whim at a time when he was tired enough to find it funny, as usual.<br>It's fine, I'll deactivate it :')</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 2:07 PM</dtime><br>Better yet, just delete it.</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:07 PM</dtime><br>Yeah, remove that bit of code from the server's bots. Let its pestilent plague be consumed by the blazing anger of cringe. Seal it within the fandom's darkest depths forever, where it belongs.</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 2:07 PM</dtime><br>You can just say you want to see it burn in hell</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:07 PM</dtime><br>... Dude I was trying to be subtle don't ruin it</td></tr>
        <tr><td><img class="icon" src="img/pfp_artie.png"></td><td><pfp><gso>CoolSkeleton03</gso></pfp> <dtime>May 1, 2016 2:07 PM</dtime><br>Anyway thanks yosh<br>You didn't think the megalovania part was too much?</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 2:08 PM</dtime><br>Eh, don't worry about it.<br>You know how it works with fanfics...<br>No matter what happens, you can always find worse than you <img class="emoji" src="http://learnwhentoquit/emj/undyne_fufu.png"><br><strike>(Case in point with Quill lmao)</strike></td></tr>
        <tr><td><img class="icon" src="img/pfp_kb.png"></td><td><pfp><bso>KangarooBrush</bso></pfp> <dtime>May 1, 2016 2:09 PM</dtime><br>Um, Lys, no offense, but Isabel is definitely the best writer I've ever seen :/</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 2:09 PM</dtime><br>Well it's not that she's a bad writer. What I mean is that her FANFICS are terrible.<br>I mean ok she writes like if she was the reincarnation of Tolkien or something.<br>BUT.<br>Have you just. READ her stuff?</td></tr>
        <tr><td><img class="icon" src="img/pfp_kb.png"></td><td><pfp><bso>KangarooBrush</bso></pfp> <dtime>May 1, 2016 2:09 PM</dtime><br>Of course I have. I was always amazed by her work <img class="emoji" src="http://learnwhentoquit/emj/toriel_um.png"></td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 2:10 PM</dtime><br>It's well written, ok.<br>But she's so attached to the canon, she rejects <yga>ANYTHING</yga> that isn't 100% confirmed to be in the game.<br>When you limit yourself so much, how can you make your story interesting? If there's literally no surprises EVER? No secrets? No imagination coming from HER?</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:10 PM</dtime><br>Haha, good point</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 2:10 PM</dtime><br>Ok she writes wonderfully and she knows how to make ANYTHING sound badass when she writes about it, but...<br>Her stories are just so boring BECAUSE she follows the canon to a T. Because we all know the canon game in depth, we can always see from a mile away what's going to happen :v<br>By now her writing only makes me snore honestly. At least if she's going to write something and we all know how it'll end, can't she make it SHORT?</td></tr>
        <tr><td><img class="icon" src="img/pfp_artie.png"></td><td><pfp><gso>CoolSkeleton03</gso></pfp> <dtime>May 1, 2016 2:11 PM</dtime><br><img class="emoji" src="http://learnwhentoquit/emj/undyne_wtf.png"><br>All hail to the one who could review calliope's fanfics lol</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 2:11 PM</dtime><br>HAHAHA BOW BEFORE YOUR FANFICTION MASTER MY PRECIOUS SLAVES <img src="http://learnwhentoquit/emj/flowey_teeth.png" class="emoji"><br>xD Seriously though someone really needs to get her off her high horse one of these days</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:11 PM</dtime><br>She brags so much about how writing stuff can only be done her way or else it has to be crap lol<br>You think she's trying to compensate on some other thing she's lacking? ;p</td></tr>
        <tr><td><img class="icon" src="img/pfp_kb.png"></td><td><pfp><bso>KangarooBrush</bso></pfp> <dtime>May 1, 2016 2:11 PM</dtime><br>That's enough, you two. Please leave her alone with this. If you want to discuss that kind of problems, then talk about it in private, and definitely not behind Isabel's back.</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:11 PM</dtime><br>... yes ma'am</td></tr>
        <tr><td><img class="icon" src="img/pfp_kb.png"></td><td><pfp><bso>KangarooBrush</bso></pfp> <dtime>May 1, 2016 2:13 PM</dtime><br>Anyway... Don't you think it's been a while since Dawn's last message? How is her run going?</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 2:13 PM</dtime><br>...true <img src="http://learnwhentoquit/emj/alphys_awkward.png" class="emoji"> It must've been at least ten minutes by now...?</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:13 PM</dtime><br>Hey, she's not bailing out NOW is she? <img src="http://learnwhentoquit/emj/toriel_mad.png" class="emoji"><br>HEY <pfp style="background-color:rgba(0,192,0,0.2); border: 2px solid transparent; border-radius:5px;"><gso>@Pineapplup</gso></pfp> YOU"RE NOT GETTING AWAY THAT EASILY I WANT MY STREAM</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 2:14 PM</dtime><br>That's weird, I don't think she would just leave us just like that...<br>It's true she looked really attached to that music sheet I found :o It looked like she was feeling embarrassed about it so I guess she composed it, but I can't read shit on musical stuff so it's not like I could understand what's wrong with it lmao<br>But don't worry, I'm sure she's fine.</td></tr>
        <tr><td><img class="icon" src="img/pfp_artie.png"></td><td><pfp><gso>CoolSkeleton03</gso></pfp> <dtime>May 1, 2016 2:14 PM</dtime><br>She's dead <img src="http://learnwhentoquit/emj/chara_jumpscare.gif" class="emoji"></td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 2:14 PM</dtime><br>She was a bit upset an hour ago, so maybe she just F4'd and now that the game's on full screen she forgot everything that's going on around it? idk<br>You know how she gets when she's deep into something u_u<br>The rest of the world just "magically disappears" and there's nothing you can do to get her out except smack her in the back of her head or whatever</td></tr>
        <tr><td><img class="icon" src="img/pfp_wdg.png"></td><td><pfp><rso>WinDows Gulim</rso></pfp> <dtime>May 1, 2016 2:14 PM</dtime><br>At this point I wonder if she'll be the first one to prove that it's possible to die during Flowey's first fight or something like that... <img src="http://learnwhentoquit/battlepfp/000-papyrus_hmm.gif" class="emoji"></td></tr>
        <tr><td><img class="icon" src="img/pfp_artie.png"></td><td><pfp><gso>CoolSkeleton03</gso></pfp> <dtime>May 1, 2016 2:14 PM</dtime><br>No but seriously you think shes past Toriel yet? XD</td></tr>
        <tr><td><img class="icon" src="img/pfp_kb.png"></td><td><pfp><bso>KangarooBrush</bso></pfp> <dtime>May 1, 2016 2:15 PM</dtime><br>Getting past Toriel isn't the biggest problem if her health is lowered down to 2 HP within the first few turns x) I'm more concerned about the rest of the Ruins honestly<br>If she finds a Vegetoid she might get into a bit more trouble...</td></tr>
        <tr><td><img class="icon" src="img/pfp_artie.png"></td><td><pfp><gso>CoolSkeleton03</gso></pfp> <dtime>May 1, 2016 2:14 PM</dtime><br>Pff at this point even the first froggit will kill her lmao</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:14 PM</dtime><br>Oh my GOD guys, have some faith in her dammit!</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 2:15 PM</dtime><br>Heh. I don't know, Jocelyn...<br>Dawn and I have been childhood friends since <yga>third grade</yga>. You know how rational and all "sciencey" I get all the time, right? But when I tell you that Dawn is literally <yga>CURSED</yga> by videogames, maybe I'm joking a bit, but it's always been THAT bad.<br>I don't know how she does it but she just always finds some sort of way to literally <rga>break the game</rga>. SOMEHOW.<br>I mean, why did YOU think making her play Undertale was that much of a big deal? :p</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:15 PM</dtime><br>Excuse me what</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 2:15 PM</dtime><br>I can't believe you joined the Plup Game without knowing what it was <rga>REALLY</rga> about XD</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:15 PM</dtime><br>Hey come on, you know me! I just roll with the flow xD<br>And since it was a joke with Dawn at the center of course I couldn't just NOT join lmao</td></tr>
        <tr><td><img class="icon" src="img/pfp_artie.png"></td><td><pfp><gso>CoolSkeleton03</gso></pfp> <dtime>May 1, 2016 2:15 PM</dtime><br>Pff ok I know Dawn always says she sucks at video games and that she's so bad there should be an award for that but a CURSE??? lol</td></tr>
        <tr><td><img class="icon" src="img/pfp_kb.png"></td><td><pfp><bso>KangarooBrush</bso></pfp> <dtime>May 1, 2016 2:15 PM</dtime><br>I'll admit I don't remember this thing about a curse either... But I guess that if YOU are saying this, then you already have evidence stacked up in order to prove your point? :p</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 2:16 PM</dtime><br>Oh you have no idea, my case is FULL of it.<br>Here's a random anecdote: there was that time when she was playing Pokemon Platinum and she found a freaking SHINY ABSOL on the FIRST TRY. It was hailing so she had to be extra careful not to KO it and all, so she decided to give it a status condition that'd make it easier to catch and then wait for the hail to weaken it.<br>So during the first turn, she paralyzed it, and then the plan was to keep switching out until it was close to the red.</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 2:16 PM</dtime><br>On the first turn, right after Dawn's Stun Spore, luckily the wild Absol is paralyzed and doesn't do anything.<br>As expected at the end of the turn, the hail hurts both Pokemon on the field.<br>But that's with the second turn that things got insane.</td></tr>
        <tr><td><img class="icon" src="img/pfp_artie.png"></td><td><pfp><gso>CoolSkeleton03</gso></pfp> <dtime>May 1, 2016 2:16 PM</dtime><br>Ok now you <yga>have</yga> to tell us xD</td></tr>
        <tr><td><img class="icon" src="img/pfp_wdg.png"></td><td><pfp><rso>WinDows Gulim</rso></pfp> <dtime>May 1, 2016 2:16 PM</dtime><br>A shiny absol? Now I don't think you told me that one but it HAD to be gold :')</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 2:16 PM</dtime><br>Second turn, Dawn decides to switch out.<br>The wild Absol uses Pursuit and nearly OHKO's Dawn's Pokemon, since that move does double damage when you try to switch out. Still, the switch occurs.<br>And then that's when the festival begins.<br><yga>Rain</yga> continues to fall. <yga>The sandstorm</yga> rages. <yga>The sunlight</yga> is strong. Oh, and hail falls too.<br>Each Pokemon is somehow hurt EVERY TIME by their <rga>ABILITIES</rga>.<br>Both Pokemon faint.<br>The end.</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:17 PM</dtime><br>but<br>how did she</td></tr>
        <tr><td><img class="icon" src="img/pfp_wdg.png"></td><td><pfp><rso>WinDows Gulim</rso></pfp> <dtime>May 1, 2016 2:17 PM</dtime><br>That was even better than I expected x'D</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:17 PM</dtime><br>bruh what the fuck???</td></tr>
        <tr><td><img class="icon" src="img/pfp_kb.png"></td><td><pfp><bso>KangarooBrush</bso></pfp> <dtime>May 1, 2016 2:17 PM</dtime><br>...<br>Oh my.</td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td colspan="2"><ul class="dlgmdt" style="margin-left:24px;"><li class="sts"><gso>Yoshua</gso> needs to reboot her brain. <dtime>May 1, 2016 2:17 PM</dtime></li></ul></td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td><img class="icon" src="img/pfp_artie.png"></td><td><pfp><gso>CoolSkeleton03</gso></pfp> <dtime>May 1, 2016 2:17 PM</dtime><br>Press f to pay respects to the kamikaze shiny absol</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:17 PM</dtime><br>f</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 2:18 PM</dtime><br>Later on I heard about that "acid rain glitch", but wherever I looked people were adamant that the glitch was only supposed to activate when it was the PLAYER who used the Pursuit move, so if it was the wild Pokemon then it wasn't supposed to happen.<br>(f yes you should've seen our faces back then OOF xD)<br>... Besides, the damage wasn't supposed to be that strong, at least not nearly strong enough to get an OHKO out of both Pokemon in just one turn.<br>So, my conclusion is, "???"</td></tr>
        <tr><td><img class="icon" src="img/pfp_artie.png"></td><td><pfp><gso>CoolSkeleton03</gso></pfp> <dtime>May 1, 2016 2:18 PM</dtime><br>F²</td></tr>
        <tr><td><img class="icon" src="img/pfp_wdg.png"></td><td><pfp><rso>WinDows Gulim</rso></pfp> <dtime>May 1, 2016 2:18 PM</dtime><br>... f<br>I think I heard about it a few years ago, yeah. Apparently it affected the HGSS games too. But it's true that this case looks weird... I wish I could look into it more.</td></tr>
        <tr><td><img class="icon" src="img/pfp_kb.png"></td><td><pfp><bso>KangarooBrush</bso></pfp> <dtime>May 1, 2016 2:18 PM</dtime><br>f</td></tr>
        <tr><td><img class="icon" src="img/pfp_wdg.png"></td><td><pfp><rso>WinDows Gulim</rso></pfp> <dtime>May 1, 2016 2:18 PM</dtime><br>Then again, what ELSE is new with all the experiments you led that involved Dawn and video games being in the same room? <img src="http://learnwhentoquit/emj/burgerpants.png" class="emoji"></td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 2:19 PM</dtime><br>I know, right? XD<br>Anyway, I won't tell every single story separately, but long story short, Dawn has a record of LITERALLY breaking every single videogame she comes across, and nobody knows how she does it, ESPECIALLY NOT HERSELF.</td></tr>
        <tr><td><img class="icon" src="img/pfp_kb.png"></td><td><pfp><bso>KangarooBrush</bso></pfp> <dtime>May 1, 2016 2:20 PM</dtime><br>This is concerning... but hilariously fascinating x'D</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 2:20 PM</dtime><br>The most common way she does it is that she activates glitches in the game that nobody knew about, or ones that are known to be insanely hard to accomplish... Except she manages to pull it off completely by accident half the time ¯\_(ツ)_/¯</td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td colspan="2"><ul class="dlgmdt" style="color:#edd91a;margin-left:24px;"><li class="sts"><gso>Yoshua</gso> has uploaded the file "<whi>2FAB4U.png</whi>" <dtime>May 1, 2016 2:21 PM</dtime></li></ul></td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:21 PM</dtime><br><img class="upload" src="http://learnwhentoquit/img/fic_006_x_2FAB4U.png"><br>sorry i had to</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 2:21 PM</dtime><br>...</td></tr>
        <tr><td><img class="icon" src="img/pfp_artie.png"></td><td><pfp><gso>CoolSkeleton03</gso></pfp> <dtime>May 1, 2016 2:21 PM</dtime><br>Haha oh shit this is too powerful</td></tr>
        <tr><td><img class="icon" src="img/pfp_kb.png"></td><td><pfp><bso>KangarooBrush</bso></pfp> <dtime>May 1, 2016 2:21 PM</dtime><br>oh boy :'D</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 2:21 PM</dtime><br>Joss I hate you<br>Nobody can criticize perfection but I still hate you</td></tr>
        <tr><td><img class="icon" src="img/pfp_wdg.png"></td><td><pfp><rso>WinDows Gulim</rso></pfp> <dtime>May 1, 2016 2:22 PM</dtime><br>Welp, I can't believe I didn't predict that you'd pull another MSPB on us xD Congrats on doing it so fast, too!<br>Your drawing skills are actually getting pretty good now o:</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:22 PM</dtime><br>Haha, tanks~ Guess it's just years of experience in shitposting 8D I wish degrees in shitposting were a thing, then I'd know what to do with my life lmao</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 2:23 PM</dtime><br>Anyway... Back to the point, if you'll allow me :p<br>NOW, do you have ANY IDEA what could happen if we tried this with <yga>UNDERTALE</yga>? <img src="http://learnwhentoquit/emj/flowey_crazy.png" class="emoji"></td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:23 PM</dtime><br>... Oh my God she's so screwed.</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 2:23 PM</dtime><br>I tried to warn you ¯\_(ツ)_/¯<br>Then again, ok, I still have to admit she's been improving. I recently tried to train her with some random rhythm game, because who's Dawn without her passion and amazing skills in music, RIGHT?<br>And uh. After a week she managed to actually finish the first level?<br>Hey, at least she even taught me something in the end.<br>On that day I learned that the rank "G" somehow EXISTS on that game???</td></tr>
        <tr><td><img class="icon" src="img/pfp_wdg.png"></td><td><pfp><rso>WinDows Gulim</rso></pfp> <dtime>May 1, 2016 2:23 PM</dtime><br>Oooh right, that one xD<br>The infamous "Backwards Secret Rank for <yga>G</yga>oobers" 8D</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:24 PM</dtime><br>PFFFFFT XD<br>Who wants to bet she'll get that glitch where Sans walks out of the screen? x)<br><a href="https://www.youtube.com/watch?v=bVyhRfDXGxQ">https://www.youtube.com/watch?v=bVyhRfDXGxQ</a><br><div class="link-thumbnail" style="border-left: 5px solid #FF0000;"><dtime>YouTube</dtime><br><b>Gl17chF4rm</b><br><a href="https://www.youtube.com/watch?v=bVyhRfDXGxQ"><b>[Undertale Glitch] Sans ignores physics</b></a><void></void><a href="https://www.youtube.com/watch?v=bVyhRfDXGxQ"><img src="http://learnwhentoquit/img/fic_006_x_videothumb.png" class="upload"></a></div></td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:24 PM</dtime><br>Still, it's too bad... I wish we could see her progress ._.</td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td colspan="2"><ul class="dlgmdt" style="color:#edd91a;margin-left:24px;"><li class="sts"><rso>Jerry.</rso> is now online. <dtime>May 1, 2016 2:26 PM</dtime></li></ul></td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td><img class="icon" src="img/pfp_kb.png"></td><td><pfp><bso>KangarooBrush</bso></pfp> <dtime>May 1, 2016 2:26 PM</dtime><br>Oh, hello!</td></tr>
        <tr><td><img class="icon" src="img/pfp_lee.png"></td><td><pfp><rso>Jerry.</rso></pfp> <dtime>May 1, 2016 2:26 PM</dtime><br>Hi folks! What's up?</td></tr>
        <tr><td><img class="icon" src="img/pfp_wdg.png"></td><td><pfp><rso>WinDows Gulim</rso></pfp> <dtime>May 1, 2016 2:26 PM</dtime><br>You won't believe what happened.<br>Dawn is playing Undertale!</td></tr>
        <tr><td><img class="icon" src="img/pfp_lee.png"></td><td><pfp><rso>Jerry.</rso></pfp> <dtime>May 1, 2016 2:26 PM</dtime><br>...<br>DUDE. YOU'RE NOT SERIOUS.</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 2:27 PM</dtime><br>THIS IS 100% SERIOUS<br>... Well we don't get to see her play for now, but I'm sure she'll have some stuff to say later :p</td></tr>
        <tr><td><img class="icon" src="img/pfp_lee.png"></td><td><pfp><rso>Jerry.</rso></pfp> <dtime>May 1, 2016 2:27 PM</dtime><br>Ugh... I wish I could've been the one, I was working on a plan to make her play too!<br>Oh well. Who's the lucky winner?</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><oso>BlueDoppler</oso></pfp> <dtime>May 1, 2016 2:27 PM</dtime><br>This girl right here <img src="http://learnwhentoquit/emj/papyrus_cape.gif" class="emoji"><br>What was the prize again? I think we talked about a special rank at some point<br>Oh and you all owe me a UT gift for the ConnectiCon meeting. I want my merch =)</td></tr>
        <tr><td><img class="icon" src="img/pfp_lee.png"></td><td><pfp><rso>Jerry.</rso></pfp> <dtime>May 1, 2016 2:29 PM</dtime><br>There, done</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><span class="wavy"><goh><span style="--i:1;">b</span><span style="--i:2;">I</span><span style="--i:3;">g</span><span style="--i:4;">W</span><span style="--i:5;">i</span><span style="--i:6;">N</span><span style="--i:7;">n</span><span style="--i:8;">E</span><span style="--i:9;">r</span><span style="--i:10;">~</span><span style="--i:11;">p</span><span style="--i:12;">R</span><span style="--i:13;">o</span><span style="--i:14;">F</span><span style="--i:15;">e</span><span style="--i:16;">S</span><span style="--i:17;">s</span><span style="--i:18;">I</span><span style="--i:19;">o</span><span style="--i:20;">N</span><span style="--i:21;">a</span><span style="--i:22;">L</span><span style="--i:23;">p</span><span style="--i:24;">L</span><span style="--i:25;">u</span><span style="--i:26;">P</span><span style="--i:27;">p</span><span style="--i:28;">E</span><span style="--i:29;">r</span></goh></span></pfp><br>Oh, you mean the rank?<br>...<br>DANG IT LEE</td></tr>
        <tr><td><img class="icon" src="img/pfp_lee.png"></td><td><pfp><rso>Jerry.</rso></pfp> <dtime>May 1, 2016 2:29 PM</dtime><br><img src="http://learnwhentoquit/emj/flowey_troll.png" class="bigemoji"></td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><span class="wavy"><goh><span style="--i:1;">b</span><span style="--i:2;">I</span><span style="--i:3;">g</span><span style="--i:4;">W</span><span style="--i:5;">i</span><span style="--i:6;">N</span><span style="--i:7;">n</span><span style="--i:8;">E</span><span style="--i:9;">r</span><span style="--i:10;">~</span><span style="--i:11;">p</span><span style="--i:12;">R</span><span style="--i:13;">o</span><span style="--i:14;">F</span><span style="--i:15;">e</span><span style="--i:16;">S</span><span style="--i:17;">s</span><span style="--i:18;">I</span><span style="--i:19;">o</span><span style="--i:20;">N</span><span style="--i:21;">a</span><span style="--i:22;">L</span><span style="--i:23;">p</span><span style="--i:24;">L</span><span style="--i:25;">u</span><span style="--i:26;">P</span><span style="--i:27;">p</span><span style="--i:28;">E</span><span style="--i:29;">r</span></goh></span></pfp><br>HOW DID YOU EVEN MANAGE TO MAKE AN ABSOLUTE GOD OF HYPERDEATH RANK XD</td></tr>
        <tr><td><img class="icon" src="img/pfp_wdg.png"></td><td><pfp><rso>WinDows Gulim</rso></pfp> <dtime>May 1, 2016 2:30 PM</dtime><br>Pfft, nice one xD</td></tr>
        <tr><td><img class="icon" src="img/pfp_kb.png"></td><td><pfp><bso>KangarooBrush</bso></pfp> <dtime>May 1, 2016 2:30 PM</dtime><br>Oh come on x)</td></tr>
        <tr><td><img class="icon" src="img/pfp_lee.png"></td><td><pfp><rso>Jerry.</rso></pfp> <dtime>May 1, 2016 2:30 PM</dtime><br>x)<br>Wait Steven<br>You're STILL online? It's like 7:30pm something here, doesn't that mean it's literally the middle of the night for you?<br>I swear you're online more and more often at the US time now<br>Doesn't that mean you're online at very weird hours for the Australian time?</td></tr>
        <tr><td><img class="icon" src="img/pfp_wdg.png"></td><td><pfp><rso>WinDows Gulim</rso></pfp> <dtime>May 1, 2016 2:31 PM</dtime><br>Ehhh, it's just a habit of getting up early and going to bed even earlier by now x)</td></tr>
        <tr><td><img class="icon" src="img/pfp_artie.png"></td><td><pfp><gso>CoolSkeleton03</gso></pfp> <dtime>May 1, 2016 2:31 PM</dtime><br>What time is it in australia rn?</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><span class="wavy"><goh><span style="--i:1;">b</span><span style="--i:2;">I</span><span style="--i:3;">g</span><span style="--i:4;">W</span><span style="--i:5;">i</span><span style="--i:6;">N</span><span style="--i:7;">n</span><span style="--i:8;">E</span><span style="--i:9;">r</span><span style="--i:10;">~</span><span style="--i:11;">p</span><span style="--i:12;">R</span><span style="--i:13;">o</span><span style="--i:14;">F</span><span style="--i:15;">e</span><span style="--i:16;">S</span><span style="--i:17;">s</span><span style="--i:18;">I</span><span style="--i:19;">o</span><span style="--i:20;">N</span><span style="--i:21;">a</span><span style="--i:22;">L</span><span style="--i:23;">p</span><span style="--i:24;">L</span><span style="--i:25;">u</span><span style="--i:26;">P</span><span style="--i:27;">p</span><span style="--i:28;">E</span><span style="--i:29;">r</span></goh></span></pfp><br>4:31 am</td></tr>
        <tr><td><img class="icon" src="img/pfp_wdg.png"></td><td><pfp><rso>WinDows Gulim</rso></pfp> <dtime>May 1, 2016 2:31 PM</dtime><br>4:31<br>wait what</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:32 PM</dtime><br>HAHAHA GOOD JORB LYS</td></tr>
        <tr><td><img class="icon" src="img/pfp_artie.png"></td><td><pfp><gso>CoolSkeleton03</gso></pfp> <dtime>May 1, 2016 2:32 PM</dtime><br>Wait a sec how did you know the answer so fast? You're not from australia too, are you? :o</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:32 PM</dtime><br>of course not Artie!! xD<br>you kno Dawn and Lys live in Peensylvania<br>wait am i typin it right???</td></tr>
        <tr><td><img class="icon" src="img/pfp_lee.png"></td><td><pfp><rso>Jerry.</rso></pfp> <dtime>May 1, 2016 2:32 PM</dtime><br>It's "Pennsylvania." And John, did you steal your sister's phone again? :p</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:32 PM</dtime><br>nah not dis time<br>but with only 1 comp at home how do u want us to b online at the same time if she takes over the home pc</td></tr>
        <tr><td><img class="icon" src="img/pfp_lee.png"></td><td><pfp><rso>Jerry.</rso></pfp> <dtime>May 1, 2016 2:33 PM</dtime><br>Fair x)</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:33 PM</dtime><br>Joss is in the bathroom rn so i dont think shed care if i take her place for a bit lol</td></tr>
        <tr><td><img class="icon" src="img/pfp_artie.png"></td><td><pfp><gso>CoolSkeleton03</gso></pfp> <dtime>May 1, 2016 2:33 PM</dtime><br>Seriously i'm still confused how did you do that Lys? You answered in like 5s top???</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><span class="wavy"><goh><span style="--i:1;">b</span><span style="--i:2;">I</span><span style="--i:3;">g</span><span style="--i:4;">W</span><span style="--i:5;">i</span><span style="--i:6;">N</span><span style="--i:7;">n</span><span style="--i:8;">E</span><span style="--i:9;">r</span><span style="--i:10;">~</span><span style="--i:11;">p</span><span style="--i:12;">R</span><span style="--i:13;">o</span><span style="--i:14;">F</span><span style="--i:15;">e</span><span style="--i:16;">S</span><span style="--i:17;">s</span><span style="--i:18;">I</span><span style="--i:19;">o</span><span style="--i:20;">N</span><span style="--i:21;">a</span><span style="--i:22;">L</span><span style="--i:23;">p</span><span style="--i:24;">L</span><span style="--i:25;">u</span><span style="--i:26;">P</span><span style="--i:27;">p</span><span style="--i:28;">E</span><span style="--i:29;">r</span></goh></span></pfp><br>I just have very good reflexes :p</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:33 PM</dtime><br>haha ye SURE<br>i bet it has somethin to do with the 2nd watch u wear on ur RIGHT wrist ;) ;) ;)</td></tr>
        <tr><td><img class="icon" src="img/pfp_wdg.png"></td><td><pfp><rso>WinDows Gulim</rso></pfp> <dtime>May 1, 2016 2:34 PM</dtime><br>You wear two watches at the same time? ._.</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><span class="wavy"><goh><span style="--i:1;">b</span><span style="--i:2;">I</span><span style="--i:3;">g</span><span style="--i:4;">W</span><span style="--i:5;">i</span><span style="--i:6;">N</span><span style="--i:7;">n</span><span style="--i:8;">E</span><span style="--i:9;">r</span><span style="--i:10;">~</span><span style="--i:11;">p</span><span style="--i:12;">R</span><span style="--i:13;">o</span><span style="--i:14;">F</span><span style="--i:15;">e</span><span style="--i:16;">S</span><span style="--i:17;">s</span><span style="--i:18;">I</span><span style="--i:19;">o</span><span style="--i:20;">N</span><span style="--i:21;">a</span><span style="--i:22;">L</span><span style="--i:23;">p</span><span style="--i:24;">L</span><span style="--i:25;">u</span><span style="--i:26;">P</span><span style="--i:27;">p</span><span style="--i:28;">E</span><span style="--i:29;">r</span></goh></span></pfp><br>SHUT UP WHO CARES ABOUT MY FASHION SENSE</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:34 PM</dtime><br>aw it has nuthin to do with fashion budy<br>everybody knos what u and steven shoud do except urselves u dorks</td></tr>
        <tr><td><img class="icon" src="img/pfp_lee.png"></td><td><pfp><rso>Jerry.</rso></pfp> <dtime>May 1, 2016 2:34 PM</dtime><br>(shit it's already time for my evening shift)<br>see you guys later!</td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td colspan="2"><ul class="dlgmdt" style="color:#e91d20;margin-left:24px;"><li class="sts"><rso>Jerry.</rso> is now offline. <dtime>May 1, 2016 2:34 PM</dtime></li></ul></td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><span class="wavy"><goh><span style="--i:1;">b</span><span style="--i:2;">I</span><span style="--i:3;">g</span><span style="--i:4;">W</span><span style="--i:5;">i</span><span style="--i:6;">N</span><span style="--i:7;">n</span><span style="--i:8;">E</span><span style="--i:9;">r</span><span style="--i:10;">~</span><span style="--i:11;">p</span><span style="--i:12;">R</span><span style="--i:13;">o</span><span style="--i:14;">F</span><span style="--i:15;">e</span><span style="--i:16;">S</span><span style="--i:17;">s</span><span style="--i:18;">I</span><span style="--i:19;">o</span><span style="--i:20;">N</span><span style="--i:21;">a</span><span style="--i:22;">L</span><span style="--i:23;">p</span><span style="--i:24;">L</span><span style="--i:25;">u</span><span style="--i:26;">P</span><span style="--i:27;">p</span><span style="--i:28;">E</span><span style="--i:29;">r</span></goh></span></pfp><br>John don't you dare<br>... WAIT LEE AM I GOING TO KEEP THAT RANK FOREVER NOW IS THAT A REAL THING???</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:34 PM</dtime><br><img src="http://learnwhentoquit/emj/button_flirt_hover.png" class="bigemoji"><br>lysven gang 4ever</td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td colspan="2"><ul class="dlgmdt" style="color:#e91d20;margin-left:24px;"><li class="sts"><gso>Yoshua</gso> has been kicked by <span class="wavy"><goh><span style="--i:1;">b</span><span style="--i:2;">I</span><span style="--i:3;">g</span><span style="--i:4;">W</span><span style="--i:5;">i</span><span style="--i:6;">N</span><span style="--i:7;">n</span><span style="--i:8;">E</span><span style="--i:9;">r</span><span style="--i:10;">~</span><span style="--i:11;">p</span><span style="--i:12;">R</span><span style="--i:13;">o</span><span style="--i:14;">F</span><span style="--i:15;">e</span><span style="--i:16;">S</span><span style="--i:17;">s</span><span style="--i:18;">I</span><span style="--i:19;">o</span><span style="--i:20;">N</span><span style="--i:21;">a</span><span style="--i:22;">L</span><span style="--i:23;">p</span><span style="--i:24;">L</span><span style="--i:25;">u</span><span style="--i:26;">P</span><span style="--i:27;">p</span><span style="--i:28;">E</span><span style="--i:29;">r</span></goh></span> <dtime>May 1, 2016 2:34 PM</dtime></li></ul></td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td><img class="icon" src="img/pfp_wdg.png"></td><td><pfp><rso>WinDows Gulim</rso></pfp> <dtime>May 1, 2016 2:35 PM</dtime><br>Whoa hey, calm down Lys :')</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><span class="wavy"><goh><span style="--i:1;">b</span><span style="--i:2;">I</span><span style="--i:3;">g</span><span style="--i:4;">W</span><span style="--i:5;">i</span><span style="--i:6;">N</span><span style="--i:7;">n</span><span style="--i:8;">E</span><span style="--i:9;">r</span><span style="--i:10;">~</span><span style="--i:11;">p</span><span style="--i:12;">R</span><span style="--i:13;">o</span><span style="--i:14;">F</span><span style="--i:15;">e</span><span style="--i:16;">S</span><span style="--i:17;">s</span><span style="--i:18;">I</span><span style="--i:19;">o</span><span style="--i:20;">N</span><span style="--i:21;">a</span><span style="--i:22;">L</span><span style="--i:23;">p</span><span style="--i:24;">L</span><span style="--i:25;">u</span><span style="--i:26;">P</span><span style="--i:27;">p</span><span style="--i:28;">E</span><span style="--i:29;">r</span></goh></span></pfp><br>Come on, he deserved it xD<br>... But yeah, sorry, I guess I AM getting a little tense rn. I'm still thinking about Dawn.<br>It's been more than half an hour by now, right? What IS she doing???</td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td colspan="2"><ul class="dlgmdt" style="color:#edd91a;margin-left:24px;"><li class="sts"><gso>Yoshua</gso> is now online. <dtime>May 1, 2016 2:35 PM</dtime></li></ul></td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><span class="wavy"><goh><span style="--i:1;">b</span><span style="--i:2;">I</span><span style="--i:3;">g</span><span style="--i:4;">W</span><span style="--i:5;">i</span><span style="--i:6;">N</span><span style="--i:7;">n</span><span style="--i:8;">E</span><span style="--i:9;">r</span><span style="--i:10;">~</span><span style="--i:11;">p</span><span style="--i:12;">R</span><span style="--i:13;">o</span><span style="--i:14;">F</span><span style="--i:15;">e</span><span style="--i:16;">S</span><span style="--i:17;">s</span><span style="--i:18;">I</span><span style="--i:19;">o</span><span style="--i:20;">N</span><span style="--i:21;">a</span><span style="--i:22;">L</span><span style="--i:23;">p</span><span style="--i:24;">L</span><span style="--i:25;">u</span><span style="--i:26;">P</span><span style="--i:27;">p</span><span style="--i:28;">E</span><span style="--i:29;">r</span></goh></span></pfp><br>oh wait I just noticed her brother sent me a text... that's weird</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:35 PM</dtime><br>Hey yall I'm back<br>And don't worry Lys, John got some noogies in revenge :p<br>It's weird yeah, I sent Dawn some texts but she doesn't answer them either</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><span class="wavy"><goh><span style="--i:1;">b</span><span style="--i:2;">I</span><span style="--i:3;">g</span><span style="--i:4;">W</span><span style="--i:5;">i</span><span style="--i:6;">N</span><span style="--i:7;">n</span><span style="--i:8;">E</span><span style="--i:9;">r</span><span style="--i:10;">~</span><span style="--i:11;">p</span><span style="--i:12;">R</span><span style="--i:13;">o</span><span style="--i:14;">F</span><span style="--i:15;">e</span><span style="--i:16;">S</span><span style="--i:17;">s</span><span style="--i:18;">I</span><span style="--i:19;">o</span><span style="--i:20;">N</span><span style="--i:21;">a</span><span style="--i:22;">L</span><span style="--i:23;">p</span><span style="--i:24;">L</span><span style="--i:25;">u</span><span style="--i:26;">P</span><span style="--i:27;">p</span><span style="--i:28;">E</span><span style="--i:29;">r</span></goh></span></pfp><br>SHIT WHAT THE HELL<br>gotta go</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:36 PM</dtime><br>????????????<br>Lyyyyys?<br>What did I miss? D:</td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td colspan="2"><ul class="dlgmdt" style="color:#e91d20;margin-left:24px;"><li class="sts"><span class="wavy"><goh><span style="--i:1;">b</span><span style="--i:2;">I</span><span style="--i:3;">g</span><span style="--i:4;">W</span><span style="--i:5;">i</span><span style="--i:6;">N</span><span style="--i:7;">n</span><span style="--i:8;">E</span><span style="--i:9;">r</span><span style="--i:10;">~</span><span style="--i:11;">p</span><span style="--i:12;">R</span><span style="--i:13;">o</span><span style="--i:14;">F</span><span style="--i:15;">e</span><span style="--i:16;">S</span><span style="--i:17;">s</span><span style="--i:18;">I</span><span style="--i:19;">o</span><span style="--i:20;">N</span><span style="--i:21;">a</span><span style="--i:22;">L</span><span style="--i:23;">p</span><span style="--i:24;">L</span><span style="--i:25;">u</span><span style="--i:26;">P</span><span style="--i:27;">p</span><span style="--i:28;">E</span><span style="--i:29;">r</span></goh></span> is now offline. <dtime>May 1, 2016 2:36 PM</dtime></li></ul></td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:36 PM</dtime><br>uuuuuuuh thanks for explaining what's going on???</td></tr>
        <tr><td><img class="icon" src="img/pfp_wdg.png"></td><td><pfp><rso>WinDows Gulim</rso></pfp> <dtime>May 1, 2016 2:36 PM</dtime><br>Uh oh, this looks serious...</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:36 PM</dtime><br>Steven, she probably sent you a DM to tell you, right?</td></tr>
        <tr><td><img class="icon" src="img/pfp_wdg.png"></td><td><pfp><rso>WinDows Gulim</rso></pfp> <dtime>May 1, 2016 2:36 PM</dtime><br>Nope :/</td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td colspan="2"><ul class="dlgmdt" style="color:#e91d20;margin-left:24px;"><li class="sts"><rso>WinDows Gulim</rso> is now offline. <dtime>May 1, 2016 2:36 PM</dtime></li></ul></td></tr>
        <tr><td colspan="2"><ul class="dlgmdt" style="color:#edd91a;margin-left:24px;"><li class="sts"><oso>Calliope Quill</oso> is now online. <dtime>May 1, 2016 2:37 PM</dtime></li></ul></td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:37 PM</dtime><br>BWAHAHA OH NOW I SEE WHAT IT IS XD<br>CALLIOPE NOW LYS HATES YOU SO MUCH SHE CAN SENSE WHEN YOU"RE ABOUT TO ARRIVE LMAO</td></tr>
        <tr><td><img class="icon" src="img/pfp_isabel.png"></td><td><pfp><oso>Calliope Quill</oso></pfp> <dtime>May 1, 2016 2:37 PM</dtime><br>... Can somebody explain what <yga>really</yga> happened?</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:37 PM</dtime><br>Nobody knows but your timing was perfect XD</td></tr>
        <tr><td><img class="icon" src="img/pfp_isabel.png"></td><td><pfp><oso>Calliope Quill</oso></pfp> <dtime>May 1, 2016 2:37 PM</dtime><br>Why does Doppler have...? Actually, I'm not even going to ask.</td></tr>
        <tr><td><img class="icon" src="img/pfp_kb.png"></td><td><pfp><bso>KangarooBrush</bso></pfp> <dtime>May 1, 2016 2:37 PM</dtime><br>That's her prize for winning the Plup Game x)</td></tr>
        <tr><td><img class="icon" src="img/pfp_isabel.png"></td><td><pfp><oso>Calliope Quill</oso></pfp> <dtime>May 1, 2016 2:38 PM</dtime><br>... In any case. I finished the newest chapter of <yga>The Last Monster</yga> in time, you can now read it on the forum if you're interested.</td></tr>
        <tr><td><img class="icon" src="img/pfp_kb.png"></td><td><pfp><bso>KangarooBrush</bso></pfp> <dtime>May 1, 2016 2:38 PM</dtime><br>Nice! I'll try to read it tonight whenever I can. But for now I'll have to leave too... ^^'</td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td colspan="2"><ul class="dlgmdt" style="color:#e91d20;margin-left:24px;"><li class="sts"><bso>KangarooBrush</bso> is now offline. <dtime>May 1, 2016 2:38 PM</dtime></li></ul></td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td><img class="icon" src="img/pfp_artie.png"></td><td><pfp><gso>CoolSkeleton03</gso></pfp> <dtime>May 1, 2016 2:38 PM</dtime><br>Sorry Isabel, I still have to read the last three first haha<br>Your chapters are so long it takes a while to read them...</td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr><tr><td colspan="2" height="200px;" style="vertical-align:middle;text-align:center;background:url(http://learnwhentoquit/img/Cutscene_Ruins_Intro_Small.png); background-size:auto 100%; background-repeat: no-repeat;background-position: center; text-shadow: 2px 0 0 black, 0 2px 0 black, 0 -2px 0 black, -2px 0 0 black, 2px 2px 0 black, 2px -2px 0 black, -2px 2px 0 black, -2px -2px 0 black;font-family:mgame;">
            <cso>blueberry11</cso><yga> has fallen into this chat!<br><br>You're new to </yga><rga>Temmie Village Forum's</rga><yga> main<br>server, aren'tcha? You must be so confused.<br>The </yga><rga>#rules</rga><yga> channel will teach you how things<br>work around here!</yga>
        </td></tr><tr><td colspan="2"><ul class="dlgmdt" style="color:#edd91a;margin-left:24px;"><li class="sts"><cso>blueberry11</cso> is now online. <dtime>May 1, 2016 2:41 PM</dtime></li></ul></td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td><img class="icon" src="img/pfp_bb.png"></td><td><pfp><cso>blueberry11</cso></pfp> <dtime>May 1, 2016 2:42 PM</dtime><br>Hi everyone!!!</td></tr>
        <tr><td><img class="icon" src="img/pfp_artie.png"></td><td><pfp><gso>CoolSkeleton03</gso></pfp> <dtime>May 1, 2016 2:42 PM</dtime><br>Oh hi! I think I recognize your pfp<br>You're one of the TVF members from last month, right?<br>Sorry every time there's a new patch on the game there's a huge wave of new members so it's hard to remember everyone</td></tr>
        <tr><td><img class="icon" src="img/pfp_bb.png"></td><td><pfp><cso>blueberry11</cso></pfp> <dtime>May 1, 2016 2:43 PM</dtime><br>yee = ^ . ^ =<br>oh i see your talking about fanfics!!<br>Which is great because i wanted to post my first ever fanfic on the forum today i'm so excited!!!</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:44 PM</dtime><br>Hey that's great! You probably must've heard of our Official Fanfic Reviewer, haha<br><strike>more like Official Fanfic Destroyer lol</strike><br>Come on Calliope, say hi to your new apprentice! <img class="emoji" src="http://learnwhentoquit/emj/flowey_wink.png"></td></tr>
        <tr><td><img class="icon" src="img/pfp_isabel.png"></td><td><pfp><oso>Calliope Quill</oso></pfp> <dtime>May 1, 2016 2:44 PM</dtime><br>...<br>"Greetings."</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:44 PM</dtime><br>Aw, she's being shy 8D<br>Looks like you'll make it out alive after all, heheheh</td></tr>
        <tr><td><img class="icon" src="img/pfp_bb.png"></td><td><pfp><cso>blueberry11</cso></pfp> <dtime>May 1, 2016 2:45 PM</dtime><br>uuuuuuuu?????? q-q</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:45 PM</dtime><br>Don't worry, I'm just joking with you. Noobies tend to scare her :p</td></tr>
        <tr><td><img class="icon" src="img/pfp_isabel.png"></td><td><pfp><oso>Calliope Quill</oso></pfp> <dtime>May 1, 2016 2:45 PM</dtime><br>You do know I can also "kick" you whenever I want, Jocelyn.</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:46 PM</dtime><br>Psh, you really have to develop a sense of humor one of these days xD<br>Remember that half the flavor text in the game is made of jokes and puns!!<br>Chara loves puns and that's canon, whether you like it or not :p</td></tr>
        <tr><td><img class="icon" src="img/pfp_isabel.png"></td><td><pfp><oso>Calliope Quill</oso></pfp> <dtime>May 1, 2016 2:46 PM</dtime><br>The "Charator" theory was never confirmed.</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:46 PM</dtime><br>DUH, between "99% canon due to the insane amount of evidence" or "explicitly Word-Of-God confirmed", you're practically the only one who still sees a difference :/<br>ANYWAY! So, dear new padawan, what's your fanfic about? :p</td></tr>
        <tr><td><img class="icon" src="img/pfp_bb.png"></td><td><pfp><cso>blueberry11</cso></pfp> <dtime>May 1, 2016 2:47 PM</dtime><br>oh! Right!!!<br>Uh I think I need some time before I can write a summary cause I don't wanna spoil!<br>but in the meantime what's your favorite AU? ^ . ^</td></tr>
        <tr><td><img class="icon" src="img/pfp_isabel.png"></td><td><pfp><oso>Calliope Quill</oso></pfp> <dtime>May 1, 2016 2:47 PM</dtime><br>...</td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td colspan="2"><ul class="dlgmdt" style="color:#e91d20;margin-left:24px;"><li class="sts"><oso>Calliope Quill</oso> has been kicked by <oso>Calliope Quill</oso>. <dtime>May 1, 2016 2:47 PM</dtime></li></ul></td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:48 PM</dtime><br>... Ooooooooh boy XD<br>Wait just a bit, I'll get her back :') Don't worry, it's not your fault, you didn't know XD</td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td colspan="2"><ul class="dlgmdt" style="color:#edd91a;margin-left:24px;"><li class="sts"><rso>WinDows Gulim</rso> is now online. <dtime>May 1, 2016 2:48 PM</dtime></li></ul></td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td><img class="icon" src="img/pfp_bb.png"></td><td><pfp><cso>blueberry11</cso></pfp> <dtime>May 1, 2016 2:48 PM</dtime><br>???? oki???? :(</td></tr>
        <tr><td><img class="icon" src="img/pfp_wdg.png"></td><td><pfp><rso>WinDows Gulim</rso></pfp> <dtime>May 1, 2016 2:48 PM</dtime><br>Well Lys isn't answering my DMs for now, so...<br>Hi there! It's your first time on the server I think, right?</td></tr>
        <tr><td><img class="icon" src="img/pfp_bb.png"></td><td><pfp><cso>blueberry11</cso></pfp> <dtime>May 1, 2016 2:48 PM</dtime><br>ye<br>but whats wrong with calliope quilil did i say something wrong???</td></tr>
        <tr><td><img class="icon" src="img/pfp_wdg.png"></td><td><pfp><rso>WinDows Gulim</rso></pfp> <dtime>May 1, 2016 2:49 PM</dtime><br>Just don't worry about it, it's nothing against you personally x)</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:49 PM</dtime><br>She'll come back in a few seconds no worries :p</td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td colspan="2"><ul class="dlgmdt" style="color:#edd91a;margin-left:24px;"><li class="sts"><oso>Calliope Quill</oso> is now online. <dtime>May 1, 2016 2:49 PM</dtime></li></ul></td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:50 PM</dtime><br>Come on now, Calliope. Just like we practiced =)</td></tr>
        <tr><td><img class="icon" src="img/pfp_isabel.png"></td><td><pfp><oso>Calliope Quill</oso></pfp> <dtime>May 1, 2016 2:50 PM</dtime><br>...<br>Which "AU" is your fanfiction about?</td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td colspan="2"><ul class="dlgmdt" style="color:#e91d20;margin-left:24px;"><li class="sts"><gso>CoolSkeleton03</gso> is now offline and left the message:<br>"<whi>Sorry dudes it's LoL time!</whi>" <dtime>May 1, 2016 2:50 PM</dtime></li></ul></td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td><img class="icon" src="img/pfp_bb.png"></td><td><pfp><cso>blueberry11</cso></pfp> <dtime>May 1, 2016 2:50 PM</dtime><br>Oh oh oh!!!<br>It's an AU I created actually!</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:51 PM</dtime><br>Oooh, even better!! :D</td></tr>
        <tr><td><img class="icon" src="img/pfp_bb.png"></td><td><pfp><cso>blueberry11</cso></pfp> <dtime>May 1, 2016 2:51 PM</dtime><br>ye!!! Its called UnderShwift ^ w ^</td></tr>
        <tr><td><img class="icon" src="img/pfp_isabel.png"></td><td><pfp><oso>Calliope Quill</oso></pfp> <dtime>May 1, 2016 2:51 PM</dtime><br>You're enjoying this way too much, Jocelyn.</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:51 PM</dtime><br>I AM AND I WON'T HIDE IT THIS IS TOO GLORIOUS XD</td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td colspan="2"><ul class="dlgmdt" style="margin-left:24px;"><li class="sts"><gso>Yoshua</gso> is preparing a LOOOOOOOOOOOOT of popcorn. John came, too. They feel like they're about to have a GREAT time. <dtime>May 1, 2016 2:52 PM</dtime></li></ul></td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td><img class="icon" src="img/pfp_isabel.png"></td><td><pfp><oso>Calliope Quill</oso></pfp> <dtime>May 1, 2016 2:52 PM</dtime><br>...<br>First of all, <yga>"UnderShwift"</yga>? "Shwift" is not even a word.</td></tr>
        <tr><td><img class="icon" src="img/pfp_bb.png"></td><td><pfp><cso>blueberry11</cso></pfp> <dtime>May 1, 2016 2:53 PM</dtime><br>its because it's a mix between Storyshift and UnderSwap... :(<br>but then Sans has to travel through AUs because of the Resets and hes trying to find a solution and he asks help to other AUs but he doesn't realize that because he did that he made Error Sans angry and now his AU is in danger!!!</td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td colspan="2"><ul class="dlgmdt" style="margin-left:24px;"><li class="sts"><gso>Yoshua</gso> would PAY to get a picture of Calliope's face rn lmao <dtime>May 1, 2016 2:53 PM</dtime></li></ul></td></tr>
        <tr><td colspan="2"><ul class="dlgmdt" style="color:#e91d20;margin-left:24px;"><li class="sts"><gso>Yoshua</gso> has been kicked by <oso>Calliope Quill</oso>. <dtime>May 1, 2016 2:54 PM</dtime></li></ul></td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td><img class="icon" src="img/pfp_bb.png"></td><td><pfp><cso>blueberry11</cso></pfp> <dtime>May 1, 2016 2:54 PM</dtime><br>??? T-T</td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td colspan="2"><ul class="dlgmdt" style="color:#edd91a;margin-left:24px;"><li class="sts"><gso>Yoshua</gso> is now online. <dtime>May 1, 2016 2:54 PM</dtime></li></ul></td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td><img class="icon" src="img/pfp_isabel.png"></td><td><pfp><oso>Calliope Quill</oso></pfp> <dtime>May 1, 2016 2:55 PM</dtime><br>Alright. You are new here, and your description in the forum shows you're only eleven years old (which by the way means that you probably should not be here, but I am too tired to open this can of worms...), so I will give you the benefit of attributing this to an error of the youth.<br>So, please listen very closely.</td></tr>
        <tr><td><img class="icon" src="img/pfp_bb.png"></td><td><pfp><cso>blueberry11</cso></pfp> <dtime>May 1, 2016 2:55 PM</dtime><br>uuuuuuh ok? ^^'</td></tr>
        <tr><td><img class="icon" src="img/pfp_isabel.png"></td><td><pfp><oso>Calliope Quill</oso></pfp> <dtime>May 1, 2016 2:55 PM</dtime><br>As you may have noticed by now, I am pretty intolerant of "AUs", but there is a very rational and sound reason behind this behavior. The reason is, we all love Undertale!<br>Why would people create entirely new universes which are not only unoriginal, but also completely abolish the meaning and depth of the canon characters as well?<br>The only kind of "AUs" I would perhaps tolerate are the ones that find their source directly from the canon, but diverge from it only because of a "what if" scenario. And in Undertale, the only ones I could think of right now is "What if Gaster's incident never occurred?", or "What if the humans did not attack Asriel and Chara when they arrived in the village?", for example.<br>But since we don't know anything whatsoever about either Gaster and his incident's whereabouts or about the surface anyway, such fanfiction could never come even close to canon, which makes it pointless and utterly ridiculous either way.</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:55 PM</dtime><br>Ok so first off, I'm pretty sure you're confusing the concept of AUs with Canon Divergence. And second off, OOOOO BOI<br>Actually, that's the point in a fanfiction, right?<br>You create a story. Your own personal story. If it's not canon then it just makes it more personal and more related to you!</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:56 PM</dtime><br>And no matter how hard you try Calliope, your fanfics are never going to be canon either<br>So it's literally the pot calling the kettle black <img class="emoji" src="http://learnwhentoquit/emj/flowey_troll.png"></td></tr>
        <tr><td><img class="icon" src="img/pfp_isabel.png"></td><td><pfp><oso>Calliope Quill</oso></pfp> <dtime>May 1, 2016 2:56 PM</dtime><br>Maybe, but you don't need to recreate the whole universe just for that! Why do you see yourself as an Undertale fan if what you're writing has nothing to do with the game? Just write an original story then, not a fanfiction that will most likely disrespect the original content.</td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td colspan="2"><ul class="dlgmdt" style="color:#edd91a;margin-left:24px;"><li class="sts"><span class="wavy"><goh><span style="--i:1;">b</span><span style="--i:2;">I</span><span style="--i:3;">g</span><span style="--i:4;">W</span><span style="--i:5;">i</span><span style="--i:6;">N</span><span style="--i:7;">n</span><span style="--i:8;">E</span><span style="--i:9;">r</span><span style="--i:10;">~</span><span style="--i:11;">p</span><span style="--i:12;">R</span><span style="--i:13;">o</span><span style="--i:14;">F</span><span style="--i:15;">e</span><span style="--i:16;">S</span><span style="--i:17;">s</span><span style="--i:18;">I</span><span style="--i:19;">o</span><span style="--i:20;">N</span><span style="--i:21;">a</span><span style="--i:22;">L</span><span style="--i:23;">p</span><span style="--i:24;">L</span><span style="--i:25;">u</span><span style="--i:26;">P</span><span style="--i:27;">p</span><span style="--i:28;">E</span><span style="--i:29;">r</span></goh></span> is now online. <dtime>May 1, 2016 2:57 PM</dtime></li></ul></td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><span class="wavy"><goh><span style="--i:1;">b</span><span style="--i:2;">I</span><span style="--i:3;">g</span><span style="--i:4;">W</span><span style="--i:5;">i</span><span style="--i:6;">N</span><span style="--i:7;">n</span><span style="--i:8;">E</span><span style="--i:9;">r</span><span style="--i:10;">~</span><span style="--i:11;">p</span><span style="--i:12;">R</span><span style="--i:13;">o</span><span style="--i:14;">F</span><span style="--i:15;">e</span><span style="--i:16;">S</span><span style="--i:17;">s</span><span style="--i:18;">I</span><span style="--i:19;">o</span><span style="--i:20;">N</span><span style="--i:21;">a</span><span style="--i:22;">L</span><span style="--i:23;">p</span><span style="--i:24;">L</span><span style="--i:25;">u</span><span style="--i:26;">P</span><span style="--i:27;">p</span><span style="--i:28;">E</span><span style="--i:29;">r</span></goh></span></pfp><br>she's nOT AT HOME<br>SHE"S NOT AT HOME<br>FUCK</td></tr>
        <tr><td><img class="icon" src="img/pfp_wdg.png"></td><td><pfp><rso>WinDows Gulim</rso></pfp> <dtime>May 1, 2016 2:57 PM</dtime><br>Wrong chat, Lys</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><span class="wavy"><goh><span style="--i:1;">b</span><span style="--i:2;">I</span><span style="--i:3;">g</span><span style="--i:4;">W</span><span style="--i:5;">i</span><span style="--i:6;">N</span><span style="--i:7;">n</span><span style="--i:8;">E</span><span style="--i:9;">r</span><span style="--i:10;">~</span><span style="--i:11;">p</span><span style="--i:12;">R</span><span style="--i:13;">o</span><span style="--i:14;">F</span><span style="--i:15;">e</span><span style="--i:16;">S</span><span style="--i:17;">s</span><span style="--i:18;">I</span><span style="--i:19;">o</span><span style="--i:20;">N</span><span style="--i:21;">a</span><span style="--i:22;">L</span><span style="--i:23;">p</span><span style="--i:24;">L</span><span style="--i:25;">u</span><span style="--i:26;">P</span><span style="--i:27;">p</span><span style="--i:28;">E</span><span style="--i:29;">r</span></goh></span></pfp><br>FUCK I"LL JUST SAY IT HERE</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:57 PM</dtime><br>Wait what?<br>What do you mean are you talking about Dawn?!</td></tr>
        <tr><td><img class="icon" src="img/pfp_bb.png"></td><td><pfp><cso>blueberry11</cso></pfp> <dtime>May 1, 2016 2:57 PM</dtime><br>?????????? WHO?????????</td></tr>
        <tr><td><img class="icon" src="img/pfp_wdg.png"></td><td><pfp><rso>WinDows Gulim</rso></pfp> <dtime>May 1, 2016 2:58 PM</dtime><br>Ok on a scale from one to ten how serious is this?</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><span class="wavy"><goh><span style="--i:1;">b</span><span style="--i:2;">I</span><span style="--i:3;">g</span><span style="--i:4;">W</span><span style="--i:5;">i</span><span style="--i:6;">N</span><span style="--i:7;">n</span><span style="--i:8;">E</span><span style="--i:9;">r</span><span style="--i:10;">~</span><span style="--i:11;">p</span><span style="--i:12;">R</span><span style="--i:13;">o</span><span style="--i:14;">F</span><span style="--i:15;">e</span><span style="--i:16;">S</span><span style="--i:17;">s</span><span style="--i:18;">I</span><span style="--i:19;">o</span><span style="--i:20;">N</span><span style="--i:21;">a</span><span style="--i:22;">L</span><span style="--i:23;">p</span><span style="--i:24;">L</span><span style="--i:25;">u</span><span style="--i:26;">P</span><span style="--i:27;">p</span><span style="--i:28;">E</span><span style="--i:29;">r</span></goh></span></pfp><br>SIXTY<br>STEVEN HER PARENTS CALLED THE POLICE<br>WHERE THE FUCK DID SHE GO<br>WHAT DO I DO</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:58 PM</dtime><br>Whoa Lys calm down!! o_o</td></tr>
        <tr><td><img class="icon" src="img/pfp_wdg.png"></td><td><pfp><rso>WinDows Gulim</rso></pfp> <dtime>May 1, 2016 2:58 PM</dtime><br>Joss is right, you need to stop panicking D:<br>I can't do much from where I am, but how's the situation? She just LEFT?</td></tr>
        <tr><td><img class="icon" src="img/pfp_bb.png"></td><td><pfp><cso>blueberry11</cso></pfp> <dtime>May 1, 2016 2:58 PM</dtime><br>O_________________O</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><span class="wavy"><goh><span style="--i:1;">b</span><span style="--i:2;">I</span><span style="--i:3;">g</span><span style="--i:4;">W</span><span style="--i:5;">i</span><span style="--i:6;">N</span><span style="--i:7;">n</span><span style="--i:8;">E</span><span style="--i:9;">r</span><span style="--i:10;">~</span><span style="--i:11;">p</span><span style="--i:12;">R</span><span style="--i:13;">o</span><span style="--i:14;">F</span><span style="--i:15;">e</span><span style="--i:16;">S</span><span style="--i:17;">s</span><span style="--i:18;">I</span><span style="--i:19;">o</span><span style="--i:20;">N</span><span style="--i:21;">a</span><span style="--i:22;">L</span><span style="--i:23;">p</span><span style="--i:24;">L</span><span style="--i:25;">u</span><span style="--i:26;">P</span><span style="--i:27;">p</span><span style="--i:28;">E</span><span style="--i:29;">r</span></goh></span></pfp><br>I don't know! She's just GONE<br>When I saw her room her PC was just open on her desk with Undertale on it!<br>Her chair and some stuff around were on the floor, but THAT'S. IT!<br>Charlie said he heard weird noises at some point but nobody saw her leave the room<br>She didn't jump out the window, did she?!</td></tr>
        <tr><td><img class="icon" src="img/pfp_bb.png"></td><td><pfp><cso>blueberry11</cso></pfp> <dtime>May 1, 2016 2:58 PM</dtime><br>what is happening?????????</td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td colspan="2"><ul class="dlgmdt" style="color:#e91d20;margin-left:24px;"><li class="sts"><cso>blueberry11</cso> has been banned by <oso>Calliope Quill</oso> for a duration of: 30 min <dtime>May 1, 2016 2:59 PM</dtime></li></ul></td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 2:59 PM</dtime><br>Isabel what the heck?!</td></tr>
        <tr><td><img class="icon" src="img/pfp_isabel.png"></td><td><pfp><oso>Calliope Quill</oso></pfp> <dtime>May 1, 2016 2:59 PM</dtime><br>I apologize. I assumed we needed some privacy for this.</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><span class="wavy"><goh><span style="--i:1;">b</span><span style="--i:2;">I</span><span style="--i:3;">g</span><span style="--i:4;">W</span><span style="--i:5;">i</span><span style="--i:6;">N</span><span style="--i:7;">n</span><span style="--i:8;">E</span><span style="--i:9;">r</span><span style="--i:10;">~</span><span style="--i:11;">p</span><span style="--i:12;">R</span><span style="--i:13;">o</span><span style="--i:14;">F</span><span style="--i:15;">e</span><span style="--i:16;">S</span><span style="--i:17;">s</span><span style="--i:18;">I</span><span style="--i:19;">o</span><span style="--i:20;">N</span><span style="--i:21;">a</span><span style="--i:22;">L</span><span style="--i:23;">p</span><span style="--i:24;">L</span><span style="--i:25;">u</span><span style="--i:26;">P</span><span style="--i:27;">p</span><span style="--i:28;">E</span><span style="--i:29;">r</span></goh></span></pfp><br>I hand't realized she was THAT upset!<br>I didn't think she'd take thaht so seriously<br>Oh my god buys is this my fault?<br>did i make a mistake by telling her to play?<br>THIS WAS JUST A GAME COME ON WHAT THE HELL IS GOING ON WHY DID SHE DO THAT?!</td></tr>
        <tr><td><img class="icon" src="img/pfp_isabel.png"></td><td><pfp><oso>Calliope Quill</oso></pfp> <dtime>May 1, 2016 2:59 PM</dtime><br>Doppler, you need to stay focused.<br>If this is so serious, we need to know what happened. When did you last hear from her?<br>Do you know any places she could have gone to? Maybe we can find her fast enough.<br>She left the chat less than an hour ago, she can't be too far.</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><span class="wavy"><goh><span style="--i:1;">b</span><span style="--i:2;">I</span><span style="--i:3;">g</span><span style="--i:4;">W</span><span style="--i:5;">i</span><span style="--i:6;">N</span><span style="--i:7;">n</span><span style="--i:8;">E</span><span style="--i:9;">r</span><span style="--i:10;">~</span><span style="--i:11;">p</span><span style="--i:12;">R</span><span style="--i:13;">o</span><span style="--i:14;">F</span><span style="--i:15;">e</span><span style="--i:16;">S</span><span style="--i:17;">s</span><span style="--i:18;">I</span><span style="--i:19;">o</span><span style="--i:20;">N</span><span style="--i:21;">a</span><span style="--i:22;">L</span><span style="--i:23;">p</span><span style="--i:24;">L</span><span style="--i:25;">u</span><span style="--i:26;">P</span><span style="--i:27;">p</span><span style="--i:28;">E</span><span style="--i:29;">r</span></goh></span></pfp><br>What the FUCK Are you being serious right now?<br>THIS IS NOT ONE OF YOUR SLUSHY FANFICTION THRILLERS, QUILL!</td></tr>
        <tr><td><img class="icon" src="img/pfp_wdg.png"></td><td><pfp><rso>WinDows Gulim</rso></pfp> <dtime>May 1, 2016 3:00 PM</dtime><br>Lys, calm down! I know you're tense but we'rejust trying to help!</td></tr>
        <tr><td><img class="icon" src="img/pfp_isabel.png"></td><td><pfp><oso>Calliope Quill</oso></pfp> <dtime>May 1, 2016 3:00 PM</dtime><br>You DO know that both my father and Sally work in the Virginia State Police, right? Pennsylvania isn't our jurisdiction so they legally can't do anything for now, but I can always ask them for advice on how to handle the situation.</td></tr>
        <tr><td><img class="icon" src="img/pfp_lys.png"></td><td><pfp><span class="wavy"><goh><span style="--i:1;">b</span><span style="--i:2;">I</span><span style="--i:3;">g</span><span style="--i:4;">W</span><span style="--i:5;">i</span><span style="--i:6;">N</span><span style="--i:7;">n</span><span style="--i:8;">E</span><span style="--i:9;">r</span><span style="--i:10;">~</span><span style="--i:11;">p</span><span style="--i:12;">R</span><span style="--i:13;">o</span><span style="--i:14;">F</span><span style="--i:15;">e</span><span style="--i:16;">S</span><span style="--i:17;">s</span><span style="--i:18;">I</span><span style="--i:19;">o</span><span style="--i:20;">N</span><span style="--i:21;">a</span><span style="--i:22;">L</span><span style="--i:23;">p</span><span style="--i:24;">L</span><span style="--i:25;">u</span><span style="--i:26;">P</span><span style="--i:27;">p</span><span style="--i:28;">E</span><span style="--i:29;">r</span></goh></span></pfp><br>WHAT MAKES YOU THINK I WANT TO LISTEN TO YOU WHEN DAWY COULD DE ANYWHETE RIGHT NOW</td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 3:00 PM</dtime><br>Lys what the fuck??? o_o</td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td colspan="2"><ul class="dlgmdt" style="color:#e91d20;margin-left:24px;"><li class="sts"><span class="wavy"><goh><span style="--i:1;">b</span><span style="--i:2;">I</span><span style="--i:3;">g</span><span style="--i:4;">W</span><span style="--i:5;">i</span><span style="--i:6;">N</span><span style="--i:7;">n</span><span style="--i:8;">E</span><span style="--i:9;">r</span><span style="--i:10;">~</span><span style="--i:11;">p</span><span style="--i:12;">R</span><span style="--i:13;">o</span><span style="--i:14;">F</span><span style="--i:15;">e</span><span style="--i:16;">S</span><span style="--i:17;">s</span><span style="--i:18;">I</span><span style="--i:19;">o</span><span style="--i:20;">N</span><span style="--i:21;">a</span><span style="--i:22;">L</span><span style="--i:23;">p</span><span style="--i:24;">L</span><span style="--i:25;">u</span><span style="--i:26;">P</span><span style="--i:27;">p</span><span style="--i:28;">E</span><span style="--i:29;">r</span></goh></span> has been banned by <rso>WinDows Gulim</rso> for a duration of: 24 h <dtime>May 1, 2016 3:00 PM</dtime></li></ul></td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td><img class="icon" src="img/pfp_isabel.png"></td><td><pfp><oso>Calliope Quill</oso></pfp> <dtime>May 1, 2016 3:00 PM</dtime><br>Good thinking, Steven. Hopefully her timeout will let her cool down and think more rationally about this...</td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td colspan="2"><ul class="dlgmdt" style="color:#e91d20;margin-left:24px;"><li class="sts"><oso>Calliope Quill</oso> has been banned by <rso>WinDows Gulim</rso> for a duration of: 24 h <dtime>May 1, 2016 3:00 PM</dtime></li></ul></td></tr>
        <tr><td colspan="2"><ul class="dlgmdt" style="color:#e91d20;margin-left:24px;"><li class="sts"><rso>WinDows Gulim</rso> is now offline. <dtime>May 1, 2016 3:00 PM</dtime></li></ul></td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td><img class="icon" src="img/pfp_joss.png"></td><td><pfp><gso>Yoshua</gso></pfp> <dtime>May 1, 2016 3:01 PM</dtime><br>Oh God</td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td colspan="2"><ul class="dlgmdt" style="color:#e91d20;margin-left:24px;"><li class="sts"><gso>Yoshua</gso> is now offline. <dtime>May 1, 2016 3:02 PM</dtime></li></ul></td></tr>
        <tr><td colspan="2" style="text-align:center;"><sts><gdi><br><br><mgame>——— This chatroom is empty ———</mgame><br><br><br></gdi></sts></td></tr>
        <tr><td colspan="2"><ul class="dlgmdt" style="color:#edd91a;margin-left:24px;"><li class="sts"><rso>Jerry.</rso> is now online. <dtime>May 1, 2016 6:55 PM</dtime></li></ul></td></tr>
        <tr><td colspan="2"><hr class="dishr"></td></tr>
        <tr><td><img class="icon" src="img/pfp_lee.png"></td><td><pfp><rso>Jerry.</rso></pfp> <dtime>May 1, 2016 6:55 PM</dtime><br>Hey guys! What did I miss? Did Dawn finish her first run?<br>...WHAT THE HELL STEVEN???</td></tr>
    </table>
    <table class="distitlend"><tr><td></td></tr></table>
</div>

<div class="dispost" id="phonindex2"><?php include('css/UTbattlescreen.php'); ?></div>
</div>
</div>
<?php include('css/sidebar.php'); ?><div id="indexlist<?= $postype ?>"><?php include('css/indtro.php'); ?><?php include('css/UTbattlescreen.php'); ?></div></body>
